### ISSUE TITLE
提点建议，流程不错，有点乱

### ISSUE THREAD

**Issue by ap1024** [TomPyer/ScrapydManagement#1]
最近我也在弄这方面的东东，有几个不错的例子，都不是太完美。
提点建议，欢迎反馈，共同进步
可以增加多个scrapyd服务器，
通过scrapyd服务器创建project
通过project上传EGG
建立JOB管理，
管理爬虫日志
分析爬虫数据

**Comment by TomPyer** [comment]
谢谢
通过scrapyd创建project和spider功能已经做好
多个scrapyd服务器我一开始没往这块想，想的是单个scrapyd服务器下多个项目来管理，如果要做这块的话应该不麻烦，加上配置然后在请求scrapyd服务器的时候按需读取。
上传egg和job管理、爬虫日志这三块，都是只要连上了scrapyd服务器都很好处理。
分析数据嘛就是后话了
嗯。。平时工作闲下来才会写一点点。。写的很慢

**Comment by jack-ZG** [comment]
综合最近使用的情况，提点意见哈；可以看，不一定要接纳。
在project使用create创建目录的时候，最好可以区分是项目文件，还是上传EGG。
在deploy的时候，最好能自定义scrapyd的project name。
在使用create创建完名称后，最好不要直接跳到自定义spider页面去，
在delete后面最好加一个能上传EGG。如果不上传，可以点EDIT，在线写爬虫。




在clients菜单里面，schedule的时候，最好不要按project name 分组。
其实按scrapyd 的分组就行 pending---running---finished这样三个就行
不然project name如果一多，显示就难看了。

最后有一个统一的调度控制，定时任务。基本上相对于管理scrapyd就差不多了。

当然还有一个，这样的系统不肯定在本地管理的，肯定会部署到服务器上面的，这样就需要一个login 登录
哈哈
罗嗦一堆。


发件人： tangxuelin
发送时间： 2018-01-24 17:13
收件人： TomPyer/ScrapydManagement
抄送： jack-ZG; Author
主题： Re: [TomPyer/ScrapydManagement] 提点建议，流程不错，有点乱 (#1)
谢谢
通过scrapyd创建project和spider功能已经做好
多个scrapyd服务器我一开始没往这块想，想的是单个scrapyd服务器下多个项目来管理，如果要做这块的话应该不麻烦，加上配置然后在请求scrapyd服务器的时候按需读取。
上传egg和job管理、爬虫日志这三块，都是只要连上了scrapyd服务器都很好处理。
分析数据嘛就是后话了
嗯。。平时工作闲下来才会写一点点。。写的很慢

**Comment by TomPyer** [comment]
调度控制用的是APScheduler，功能做的差不多了，用来关闭，启动爬虫等

登录相关的功能做起来容易，一开始有打算先做，后来觉得调试麻烦，就先关了放一边了

分组嘛，我也觉得按照pending---running---finished分比较好，但是也需要有页面展示所有的项目和爬虫，所以就添加pending页面就可以，运行中和已结束爬虫有两个页面展示了

我开始的想法就是在线写爬虫，上传egg的功能也是需要写好，要不然到时候自己现有的爬虫这么多，还是打包的方便一些

谢谢您的建议

**Comment by ap1024** [comment]
同步学习啊
